### ISSUE TITLE
Bar chart horizontal

### ISSUE THREAD

**Issue by suryadana** [bbonnin/vue-morris#8]
I want to create a horizontal bar chart, I can create with this library?

**Comment by pierresh** [comment]
I have never used this fork of Morris.js with Vue, but with original one you just need to set the option _horizontal: true_

**Comment by bbonnin** [comment]
The problem is that `horizontal` option is only available as the version 0.5.1 of morris.js that is NOT available on npm repository. The latest release of morrisjs/morrisjs in npm is 0.5.0.
If you find a forked version of morrisjs v0.5.1 available on npm, use it and add the horizontal attribute with the `<bar-chart>` tag.

PS: vue-morris is not a fork but just a wrapper.  ;-)

**Comment by suryadana** [comment]
Ok i will try that thank for you support. 👍
